name: Publish Package

on:
  push:
    branches: [ release ]

jobs:
  publish:
    env:
      NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
          registry-url: https://registry.npmjs.org/
      - name: Install Dependencies
        run: npm ci
      - name: Build the Project
        run: npm run build
      - name: Perform SonarQube Scan
        run: npm run sonar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_LOGIN: ${{ secrets.SONAR_LOGIN }}
      - name: Publish Package
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
